schema-version = 1

[package]
title = "Basic UI React Native Application for project vegashell"
version = "0.1.0"
id = "com.invicttusx.flappybird"

[components]
[[components.interactive]]
id = "com.invicttusx.flappybird.main"
runtime-module = "/com.amazon.kepler.keplerscript.runtime.loader_2@IKeplerScript_2_0"
launch-type = "singleton"
categories = ["com.amazon.category.main"]
