schema-version = 1

[package]
title = "FlappyBird"
version = "0.1.0"
id = "com.invicttusx.flappybird"

[components]
[[components.interactive]]
id = "com.invicttusx.flappybird.main"
runtime-module = "/com.amazon.kepler.keplerscript.runtime.loader_2@IKeplerScript_2_0"
launch-type = "singleton"
categories = ["com.amazon.category.main"]

[wants]
[[wants.service]]
id = "com.amazon.media.playersession.service"

[[wants.service]]
id = "com.amazon.webview.renderer_service"

[[wants.service]]
id = "com.amazon.inputmethod.service"

[[wants.service]]
id = "com.amazon.audio.stream"

[[wants.service]]
id = "com.amazon.audio.control"

[[wants.service]]
id = "com.amazon.kepler.ucc.publisher"

[[wants.service]]
id = "com.amazon.mediametrics.service"

[[wants.service]]
id = "com.amazon.gipc.uuid.*"

[[wants.service]]
id = "com.amazon.mediabuffer.service"

[[wants.service]]
id = "com.amazon.mediatransform.service"

[[wants.service]]
id = "com.amazon.audio.system"

[offers]
[[offers.service]]
id = "com.amazon.gipc.uuid.*"